name: Deploy to server

on: 
  push:
    branches:
      - main

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo ${{ steps.step_1.outputs.my_variable }}

      - name: Action
        uses: actions/checkout@v4
  
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: 
      - first-job
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito
      SALIDA: ${{ needs.first_job.outputs.salidad }}

    steps:
      - name: Hola Mundo 2
        run: echo "Hola Mundo Segundo ${{ github.ref }} - $NAME - $SALIDA"