name: Deploy to server

on: 
  push:
    branches:
      - main

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest

    steps:
      - name: Working dir
        run: echo $GITHUB_OUTPUT

      - name: Action
        uses: actions/checkout@v4
  
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: 
      - first-job
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: Hola Mundo 2
        run: echo "Hola Mundo Segundo ${{ github.ref }} - $NAME"