name: Deploy to server

on: 
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo 1
        run: echo "Hola Mundo Primero"
  
  second-job:
    needs: 
      - first-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo 2
        run: echo "Hola Mundo Segundo"